# Import Libraries

In [4]:
import pandas as pd
import numpy as np
import ast #Hello

# Load Data

In [19]:
# Read in checkpoint 3
final_df = pd.read_csv('checkpoint_3.csv')
# df_read_in.info()
final_df['lat_lon'] = final_df['lat_lon'].apply(ast.literal_eval).apply(lambda x: (float(x[0]), float(x[1]))) # Change to tuple of floats

In [22]:
final_df

,town,flat_type,flat_model,floor_area_sqm,street_name,resale_price,month,lease_commence_date,storey_range,_id,...,num_MI_sch_1km_radius,closest_Uni_sch_dist,closest_Uni_sch,num_Uni_sch_1km_radius,closest_mall_dist,closest_mall,num_mall_1km_radius,closest_park_dist,closest_park,num_park_1km_radius
0,ANG MO KIO,2 ROOM,Improved,44.0,ANG MO KIO AVE 10,232000.0,2017-01,1979.0,10 TO 12,1,...,0,7408.201434,Singapore Management University,0,1013.992058,AMK Hub,0,1032.586022,Ang Mo Kio Town Garden East,0
1,ANG MO KIO,3 ROOM,New Generation,67.0,ANG MO KIO AVE 4,250000.0,2017-01,1978.0,01 TO 03,2,...,0,8371.125772,Singapore University of Social Sciences,0,894.265975,Broadway Plaza,1,658.451197,Ang Mo Kio Town Garden West,2
2,ANG MO KIO,3 ROOM,New Generation,67.0,ANG MO KIO AVE 5,262000.0,2017-01,1980.0,01 TO 03,3,...,0,8802.805943,Singapore University of Social Sciences,0,1525.573038,Broadway Plaza,0,1111.238041,Ang Mo Kio Town Garden West,0
3,ANG MO KIO,3 ROOM,New Generation,68.0,ANG MO KIO AVE 10,265000.0,2017-01,1980.0,04 TO 06,4,...,0,7897.637286,Singapore Management University,0,893.795634,myVillage At Serangoon Garden,1,898.087299,Ang Mo Kio Town Garden East,1
4,ANG MO KIO,3 ROOM,New Generation,67.0,ANG MO KIO AVE 5,265000.0,2017-01,1980.0,01 TO 03,5,...,0,8807.296192,Singapore University of Social Sciences,0,1569.306143,Broadway Plaza,0,1155.199842,Ang Mo Kio Town Garden West,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149321,YISHUN,EXECUTIVE,Maisonette,146.0,YISHUN CTRL,800000.0,2023-03,1988.0,10 TO 12,149322,...,0,13379.711491,Singapore University of Social Sciences,0,432.877723,Junction Nine,2,279.490328,Yishun Pond Park,1
149322,YISHUN,EXECUTIVE,Maisonette,146.0,YISHUN RING RD,800000.0,2023-03,1988.0,01 TO 03,149323,...,0,13232.047301,Singapore University of Social Sciences,0,931.337725,Wisteria Mall,2,661.649827,Yishun Pond Park,1
149323,YISHUN,EXECUTIVE,Apartment,142.0,YISHUN RING RD,770000.0,2023-03,1988.0,04 TO 06,149324,...,0,13428.149563,Singapore Institute of Technology,0,739.745345,Junction Nine,1,825.343534,Yishun Pond Park,1
149324,YISHUN,EXECUTIVE,Maisonette,146.0,YISHUN RING RD,818000.0,2023-03,1987.0,10 TO 12,149325,...,0,11979.803115,Singapore University of Social Sciences,0,965.509600,Northpoint City,1,976.514291,Sembawang Park,1
149325,YISHUN,EXECUTIVE,Apartment,164.0,YISHUN ST 61,975000.0,2023-03,1992.0,01 TO 03,149326,...,0,12422.066468,Singapore University of Social Sciences,0,439.848531,Wisteria Mall,2,761.073177,Yishun Pond Park,1

# One Hot Encoding

# Target Encoding